@host=http://localhost:5175

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMzc0NTBiMi05MDlmLTQ2ZTYtOGFjYi01MTBkNDQ3YzkxNDAiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiI2ODAwNGVkZC02OGQzLTQ4NTctOTYxNS1mODU5MzVmMWNiYzMiLCJleHAiOjE2OTA3ODQ3NTIsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ._P2GlbKG2c3fQXZe2x3QsS3AyAIeLFCaWWxBxmrkIdU